#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/byblog?useUnicode=true&characterEncoding=utf8
    username: root
    password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    com.byblog.system.service.impl: trace
    com.byblog.system..controller: trace
